//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHeader
    {
        public int id { get; set; }
        public int userId { get; set; }
        public System.DateTime transactionDate { get; set; }
        public string status { get; set; }
    
        public virtual TransactionDetail TransactionDetail { get; set; }
        public virtual User User { get; set; }
    }
}
