//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int transactionId { get; set; }
        public int makeupId { get; set; }
        public int quantity { get; set; }
    
        public virtual Makeup Makeup { get; set; }
        public virtual TransactionHeader TransactionHeader { get; set; }
    }
}
